########################################################################
# Name  : makefile for Minishell
# Author: Julia Nelson
# Date  : June 25, 2021
# Pledge: "I pledge my honor that I have abided by the Stevens Honor System."
#######################################################################

CC=gcc
CFLAGS=-Wextra -g

minishell: main.c
	$(CC) $(CFLAGS) -o minishell main.c

clean:
	rm -f minishell
